# OBJS	= Find_Windows.o main_Cookie_Clicker.o
# SOURCE	= Find_Windows.cpp main_Cookie_Clicker.cpp
# HEADER	= Find_Windows.h
# OUT	= test
# CC	 = g++
# FLAGS	 = -g -c -Wall
# LFLAGS	 = 

# all: $(OBJS)
# 	$(CC) -g $(OBJS) -o $(OUT) $(LFLAGS)

# Find_Windows.o: Find_Windows.cpp
# 	$(CC) $(FLAGS) Find_Windows.cpp -std=c++11

# main_Cookie_Clicker.o: main_Cookie_Clicker.cpp
# 	$(CC) $(FLAGS) main_Cookie_Clicker.cpp -std=c++11


# clean:
# 	rm -f $(OBJS) $(OUT)